const AUTH_LOGIN_START = 'AUTH_LOGIN_START'
const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR'
const AUTH_LOGOUT = 'AUTH_LOGOUT'
export {
  AUTH_LOGIN_START,
  AUTH_LOGIN_SUCCESS,
  AUTH_LOGIN_ERROR,
  AUTH_LOGOUT
}