const TASKS_FETCH_START = 'TASKS_FETCH_START'
const TASKS_FETCH_SUCCESS = 'TASKS_FETCH_SUCCESS'
const TASKS_FETCH_ERROR = 'TASKS_FETCH_ERROR'
const TASKS_PAGINATION_CHANGE = 'TASKS_PAGINATION_CHANGE'

export {
  TASKS_FETCH_START,
  TASKS_FETCH_SUCCESS,
  TASKS_FETCH_ERROR,
  TASKS_PAGINATION_CHANGE
}