const TASKS_FETCH_START = 'TASKS_FETCH_START'
const TASKS_FETCH_SUCCESS = 'TASKS_FETCH_SUCCESS'
const TASKS_FETCH_ERROR = 'TASKS_FETCH_ERROR'
const TASKS_PAGINATION_CHANGE = 'TASKS_PAGINATION_CHANGE'
const TASKS_SORT_CHANGE = 'TASKS_SORT_CHANGE'
const TASKS_SORTDIRECTION_CHANGE = 'TASKS_SORTDIRECTION_CHANGE'
const TASKS_ADD_MESSAGE = 'TASKS_ADD_MESSAGE'

export {
  TASKS_FETCH_START,
  TASKS_FETCH_SUCCESS,
  TASKS_FETCH_ERROR,
  TASKS_PAGINATION_CHANGE,
  TASKS_SORTDIRECTION_CHANGE,
  TASKS_SORT_CHANGE,
  TASKS_ADD_MESSAGE
}